<?xml version="1.0" encoding="utf-16" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="NUnit.Tests.Assemblies.MockTestFixture" total="8" errors="1" failures="1" not-run="3" inconclusive="1" ignored="1" skipped="0" invalid="2" date="2016-05-25" time="12:38:21">
  <environment nunit-version="3.3.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\Projects\GitHub\nunit\bin\Debug\net-4.5" machine-name="UNIT-728" user="Nikolay.Pianikov" user-domain="LABS" />
  <culture-info current-culture="ru-RU" current-uiculture="en-US" />
  <test-suite type="TestFixture" name="MockTestFixture" description="Fake Test Fixture" executed="True" result="Failure" success="False" time="0.009" asserts="0">
    <categories>
      <category name="FixtureCategory" />
    </categories>
    <properties>
      <property name="Description" value="Fake Test Fixture" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
      <stack-trace />
    </failure>
    <results>
      <test-case name="TestWithDescription" description="Mock Test #1" executed="True" result="Success" success="True" time="0.000" asserts="0">
        <categories>
          <category name="MockCategory" />
        </categories>
        <properties>
          <property name="Description" value="Mock Test #1" />
          <property name="Severity" value="Critical" />
        </properties>
      </test-case>
      <test-case name="NonPublicTest" executed="True" result="Failure" success="False" time="0.001" asserts="0">
        <properties>
          <property name="_SKIPREASON" value="Method is not public" />
        </properties>
        <failure>
          <message><![CDATA[Method is not public]]></message>
          <stack-trace />
        </failure>
      </test-case>
      <test-case name="FailingTest" executed="True" result="Failure" success="False" time="0.006" asserts="0">
        <failure>
          <message><![CDATA[Intentional failure]]></message>
          <stack-trace><![CDATA[at NUnit.Tests.Assemblies.MockTestFixture.FailingTest() in C:\Projects\GitHub\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 131
]]></stack-trace>
        </failure>
      </test-case>
      <test-case name="IgnoreTest" executed="False" result="Ignored">
        <properties>
          <property name="_SKIPREASON" value="Ignore Message" />
        </properties>
        <reason>
          <message><![CDATA[Ignore Message]]></message>
        </reason>
      </test-case>
      <test-case name="ExplicitTest" executed="False" result="Skipped" />
      <test-case name="NotRunnableTest" executed="True" result="Failure" success="False" time="0.000" asserts="0">
        <properties>
          <property name="_SKIPREASON" value="No arguments were provided" />
        </properties>
        <failure>
          <message><![CDATA[No arguments were provided]]></message>
          <stack-trace />
        </failure>
      </test-case>
      <test-case name="InconclusiveTest" executed="True" result="Inconclusive" success="False" time="0.001" asserts="0" />
      <test-case name="TestWithException" executed="True" result="Error" success="False" time="0.002" asserts="0">
        <failure>
          <message><![CDATA[System.Exception : Intentional Exception]]></message>
          <stack-trace><![CDATA[   at NUnit.Tests.Assemblies.MockTestFixture.MethodThrowsException() in C:\Projects\GitHub\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 157
   at NUnit.Tests.Assemblies.MockTestFixture.TestWithException() in C:\Projects\GitHub\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 152]]></stack-trace>
        </failure>
      </test-case>
    </results>
  </test-suite>
</test-results>
